language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli bower
install: npm install
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: E1LpQjenFPgIGbXN5p+J+wI/6Z0E8QMR7OQU1Ye1O3i23WDB7STOyTA6LZc/5Kuxx9Yqe2eTX15M05Q12mwdVnUnmWD/Iv1ZS35JX1fbF+8VAer5Ulu379Fek0QLbiFC/FoRuV571CFy2BzLSstHGNcq2NdnXAe3auiBtoWgm64=
  app:
    development: newlegacyinc-app-server-dev
